// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {control} from '../models';
import {vault} from '../models';

export function Bootstrap():Promise<control.Bootstrap>;

export function CreateFundingTask(arg1:string,arg2:string):Promise<control.FundingTask>;

export function CreateVault(arg1:string):Promise<void>;

export function DeleteFundingTask(arg1:string):Promise<void>;

export function DeleteStrategy(arg1:string):Promise<void>;

export function ExitStrategy(arg1:string,arg2:string):Promise<void>;

export function ExportFundingBatches(arg1:string):Promise<string>;

export function ExportGMGN(arg1:string):Promise<string>;

export function FetchLatestLaunch():Promise<control.LaunchPreset>;

export function FundingState():Promise<control.FundingState>;

export function GenerateFundingWallets(arg1:string):Promise<string>;

export function GenerateMnemonic():Promise<string>;

export function ImportMnemonic(arg1:string,arg2:number,arg3:string):Promise<Array<vault.Summary>>;

export function ImportPrivateKeys(arg1:string,arg2:string):Promise<Array<vault.Summary>>;

export function LockVault():Promise<void>;

export function NewStrategy():Promise<control.Strategy>;

export function PreflightStrategy(arg1:string):Promise<string>;

export function ResetStrategy(arg1:string):Promise<control.Strategy>;

export function RunInitCheck():Promise<control.InitStatus>;

export function SaveSettings(arg1:control.Settings):Promise<void>;

export function SaveStrategy(arg1:control.Strategy):Promise<control.Strategy>;

export function SetFundingWithdrawCold(arg1:string):Promise<void>;

export function StartFundingTask(arg1:string,arg2:string):Promise<void>;

export function StartStrategy(arg1:string,arg2:string):Promise<void>;

export function StopFundingTask(arg1:string):Promise<void>;

export function StopStrategy(arg1:string):Promise<void>;

export function UnlockVault(arg1:string):Promise<void>;
