// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {control} from '../models';
import {vault} from '../models';

export function Bootstrap():Promise<control.Bootstrap>;

export function CreateVault(arg1:string):Promise<void>;

export function DeleteStrategy(arg1:string):Promise<void>;

export function ExitStrategy(arg1:string,arg2:string):Promise<void>;

export function ExportGMGN(arg1:string):Promise<string>;

export function GenerateMnemonic():Promise<string>;

export function ImportMnemonic(arg1:string,arg2:number,arg3:string):Promise<Array<vault.Summary>>;

export function ImportPrivateKeys(arg1:string,arg2:string):Promise<Array<vault.Summary>>;

export function LockVault():Promise<void>;

export function NewStrategy():Promise<control.Strategy>;

export function PreflightStrategy(arg1:string):Promise<string>;

export function SaveSettings(arg1:control.Settings):Promise<void>;

export function SaveStrategy(arg1:control.Strategy):Promise<control.Strategy>;

export function StartStrategy(arg1:string,arg2:string):Promise<void>;

export function StopStrategy(arg1:string):Promise<void>;

export function UnlockVault(arg1:string):Promise<void>;
