// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Bootstrap() {
  return window['go']['main']['App']['Bootstrap']();
}

export function CreateVault(arg1) {
  return window['go']['main']['App']['CreateVault'](arg1);
}

export function DeleteStrategy(arg1) {
  return window['go']['main']['App']['DeleteStrategy'](arg1);
}

export function ExportGMGN(arg1) {
  return window['go']['main']['App']['ExportGMGN'](arg1);
}

export function GenerateMnemonic() {
  return window['go']['main']['App']['GenerateMnemonic']();
}

export function ImportMnemonic(arg1, arg2, arg3) {
  return window['go']['main']['App']['ImportMnemonic'](arg1, arg2, arg3);
}

export function ImportPrivateKeys(arg1, arg2) {
  return window['go']['main']['App']['ImportPrivateKeys'](arg1, arg2);
}

export function LockVault() {
  return window['go']['main']['App']['LockVault']();
}

export function NewStrategy() {
  return window['go']['main']['App']['NewStrategy']();
}

export function PreflightStrategy(arg1) {
  return window['go']['main']['App']['PreflightStrategy'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SaveStrategy(arg1) {
  return window['go']['main']['App']['SaveStrategy'](arg1);
}

export function StartStrategy(arg1, arg2) {
  return window['go']['main']['App']['StartStrategy'](arg1, arg2);
}

export function StopStrategy(arg1) {
  return window['go']['main']['App']['StopStrategy'](arg1);
}

export function UnlockVault(arg1) {
  return window['go']['main']['App']['UnlockVault'](arg1);
}
